# Generated by Django 4.1.3 on 2023-08-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StaffApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='name_in_latin',
            new_name='name',
        ),
    ]
